ip: 127.0.0.1 # server ip
port: 2777 # server tcp port

watch: # read file path and service name
  - path: C:\Temp\test\log.txt
    service: apache

  - path: C:\Temp\test2\log.txt
    service: logging2