spring:
  datasource:
    hikari:
      auto-commit: false
  profiles:
    default: in_memory
    group:
      memory : mem_db, mem_idx
      embedded : emd_db, emd_idx
  jpa:
    properties:
      hibernate:
        search:
          backend:
            analysis.configurer: class:com.example.logserver.config.LuceneAnalyser
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    jdbc:
      sqlonly: warn
      sqltiming: warn
      resultsettable: warn
      audit: warn
      resultset: warn
      connection: warn

---

spring:
  datasource:
    url: jdbc:h2:mem:log_db
    username: sa
    password:

  config:
    activate:
      on-profile: mem_db
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual: true
    hibernate:
      ddl-auto: create
---

spring:
  config:
    activate:
      on-profile: mem_idx
  jpa:
    properties:
      hibernate:
        search:
          schema_management.strategy: drop-and-create
          backend:
            directory.type: local-heap
---

---
spring:
  datasource:
    url: jdbc:h2:~/log_db
    username: sa
    password:

  config:
    activate:
      on-profile: emd_db
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual: true
    hibernate:
      ddl-auto: create
---

spring:
  config:
    activate:
      on-profile: emd_idx
  jpa:
    properties:
      hibernate:
        search:
          schema_management.strategy: drop-and-create
          backend:
            directory.root: ./indexed
---

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/demodb
    username: demi
    password: demi1234!!
  jpa:
    hibernate:
      ddl-auto: update
